service: geoip-goingcloudnative-template
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1

functions:
  geoip:
    handler: geoip.get
    events:
      - http:
          path: /json
          method: get